default_context:
  project_name: 'Vehicle monitoring and analysis software'
  project_slug: 'tracker'
  domain_main: 'tracker.olekczubiak.tk'
  domain_staging: 'stag.tracker.olekczubiak.tk'
  docker_swarm_stack_name_main: 'tracker-olekczubiak-tk'
  docker_swarm_stack_name_staging: 'stag-tracker-olekczubiak-tk'
  secret_key: 'aa44e0e8f6160be1d8f5c36f9de00f762cee9975581181556a26beb395a7b358'
  first_superuser: 'admin@tracker.olekczubiak.tk'
  first_superuser_password: 'admin1'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.tracker.olekczubiak.tk", "https://stag.tracker.olekczubiak.tk", "https://tracker.olekczubiak.tk", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@tracker.olekczubiak.tk'
  postgres_password: 'olek123'
  pgadmin_default_user: 'admin@tracker.olekczubiak.tk'
  pgadmin_default_user_password: 'admin1'
  traefik_constraint_tag: 'tracker.olekczubiak.tk'
  traefik_constraint_tag_staging: 'stag.tracker.olekczubiak.tk'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin1'
  sentry_dsn: ''
  docker_image_prefix: 'github.com/olekczubiak/Praca-dyplomowa'
  docker_image_backend: 'github.com/olekczubiak/Praca-dyplomowa/backend'
  docker_image_celeryworker: 'github.com/olekczubiak/Praca-dyplomowa/celeryworker'
  docker_image_frontend: 'github.com/olekczubiak/Praca-dyplomowa/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
